import os
import time
from playwright.sync_api import sync_playwright

def verify_solitaire():
    file_path = os.path.abspath("index.html")
    file_url = f"file://{file_path}"

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.set_viewport_size({"width": 1280, "height": 720})
        page.goto(file_url)

        # Open Solitaire from Desktop
        print("Opening Solitaire...")
        # Solitaire icon should be on desktop
        page.locator(".icon:has-text('Solitaire')").click()

        # Wait for window
        print("Waiting for Solitaire window...")
        window = page.locator(".solitaire-window")
        window.wait_for(state="visible", timeout=2000)

        # Verify UI components
        print("Verifying UI components...")
        if page.locator(".solitaire-stock-waste").is_visible():
            print("Stock/Waste visible.")
        else:
            print("Stock/Waste NOT visible.")
            exit(1)

        if page.locator(".solitaire-foundations").is_visible():
            print("Foundations visible.")
        else:
            print("Foundations NOT visible.")
            exit(1)

        if page.locator(".solitaire-bottom-row").is_visible():
            print("Tableau visible.")
        else:
            print("Tableau NOT visible.")
            exit(1)

        # Check for cards
        # We expect 7 columns with 1..7 cards = 28 cards.
        # Plus stock (rest).
        # Cards in tableau are generated by JS.
        # Let's wait a bit for JS to render
        time.sleep(1)

        cards = page.locator(".solitaire-card")
        count = cards.count()
        print(f"Found {count} cards.")

        if count < 28:
            print("Error: Too few cards found.")
            exit(1)

        # Take screenshot
        page.screenshot(path="verification/solitaire_open.png")
        print("Screenshot saved to verification/solitaire_open.png")

        browser.close()

if __name__ == "__main__":
    verify_solitaire()
